### PR TITLE
Issue #560 by holt83: Use entity metadata wrappers when looking up library for event in ding_place2book_event_op().

### PR DESCRIPTION
**Pull request by holt83**

### CODE REVIEW

**Comment by cableman** [comment]
The PR https://github.com/ding2/ding_place2book/pull/2 replaces this PR and is based on the idea here.

**Comment by holt83** [comment]
That sounds good :)

Wierd that my solution works on my setup though. I followed the instructions at https://www.drupal.org/documentation/entity-metadata-wrappers (Get first value of multifield (multiple-value field))

**Comment by cableman** [comment]
I would have expected your solution to work, but Organic group references are somewhat strange and it always returned FALSE on a clean DDB CMS installation :-) 

So it took a lot of testing to get the other solution running. It uses the wrapper and the "value" function, which returns the entity's for the libraries selected and then as default only selects the first one. I moved this into a helper function as it needs to be called in more than one place.

**Comment by holt83** [comment]
Thanks for the explanation :) 

I suspected that the problem had something to do with the OG module.

**Pull request closed without merging**
